import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const uni_sans = localFont({
  src: [
    {path: "./font/uni_sans/Uni Sans Heavy.otf", weight: "900", style: "normal" },
    { path: "./font/uni_sans/Uni Sans Bold.otf", weight: "700", style: "normal" },
    { path: "./font/uni_sans/Uni Sans SemiBold.otf", weight: "600", style: "normal" },
    { path: "./font/uni_sans/Uni Sans Regular.otf", weight: "400", style: "normal" },
    { path: "./font/uni_sans/Uni Sans Light.otf", weight: "300", style: "normal" },
    { path: "./font/uni_sans/Uni Sans Thin.otf", weight: "200", style: "normal" }
  ],

  variable: "--font-uni-sans",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${uni_sans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
